exports.entryTypesWithText = [
    {value: "journalEntry", text: "Journal Entry"},
    {value: "thought", text: "Thought"},
    {value: "otherNote", text: "Other Note"},
    {value: "movie", text: "Movie"},
    {value: "show", text: "Show"},
    {value: "song", text: "Song"},
    {value: "album", text: "Album"},
    {value: "band", text: "Band"},
    {value: "book", text: "Book"},
    {value: "videoGame", text: "Video Game"},
    {value: "boardGame", text: "Board Game"},
    {value: "otherGame", text: "Other Game"},
    {value: "podcast", text: "Podcast"},
    {value: "youtube", text: "YouTube"},
    {value: "resource", text: "Resource"},
    {value: "website", text: "Website"},
    {value: "restaurant", text: "Restaurant"},
    {value: "trip", text: "Trip"},
    {value: "flight", text: "Flight"},
    {value: "hotel", text: "Hotel"},
    {value: "roadTripStop", text: "Road Trip Stop"},
    {value: "nightOut", text: "Night Out"},
    {value: "dayTrip", text: "Day Trip"},
    {value: "hike", text: "Hike"},
    {value: "run", text: "Run"},
    {value: "otherExercise", text: "Other Exercise"},
    {value: "onATeam", text: "On A Team"},
    {value: "gymMembership", text: "Gym Membership"},
    {value: "otherMembership", text: "Other Membership"},
    {value: "hobby", text: "Hobby"},
    {value: "project", text: "Project"},
    {value: "habit", text: "Habit"},
    {value: "relationship", text: "Relationship"},
    {value: "friendship", text: "Friendship"},
    {value: "childhoodMilestones", text: "Childhood Milestones"},
    {value: "birthday", text: "Birthday"},
    {value: "holiday", text: "Holiday"},
    {value: "familyGathering", text: "Family Gathering"},
    {value: "pet", text: "Pet"},
    {value: "job", text: "Job"},
    {value: "residence", text: "Residence"},
    {value: "car", text: "Car"},
    {value: "school", text: "School"},
    {value: "eventWedding", text: "Wedding"},
    {value: "eventSports", text: "Sporting Event"},
    {value: "eventConcert", text: "Concert"},
    {value: "eventParty", text: "Party"},
    {value: "eventConference", text: "Conference"},
    {value: "eventOther", text: "Other Event"},
    {value: "achievementOrAward", text: "Achievement or Award"},
    {value: "majorPurchase", text: "Major Purchase"},
    {value: "lifeEvent", text: "Life Event"},
    {value: "picture", text: "Picture"},
    {value: "other", text: "Other"}
];

exports.entryTypes = [
    "journalEntry", "thought", "otherNote", "movie", "show", 
    "song", "album", "band", "book", "restaurant", "trip", "flight", 
    "relationship", "friendship", "childhoodMilestones", "pet", 
    "job", "residence", "car", "school", "eventWedding", "eventSports", "eventConference",
    "eventConcert", "eventParty", "eventOther", "roadTripStop",
    "achievementOrAward", "majorPurchase", "lifeEvent", "picture", 
    "nightOut", "dayTrip", "hike", "other", "hotel", "project",
    "videoGame", "boardGame", "otherGame", "podcast", "youtube",
    "resource", "website", "gymMembership", "otherMembership",
    "onATeam", "otherExercise", "run", "hobby", "habit", "birthday",
    "holiday", "familyGathering"
];