exports.entryTypesWithText = [
    {value: "journalEntry", text: "Journal Entry"},
    {value: "thought", text: "Thought"},
    {value: "otherNote", text: "Other Note"},
    {value: "movie", text: "Movie"},
    {value: "show", text: "Show"},
    {value: "song", text: "Song"},
    {value: "album", text: "Album"},
    {value: "band", text: "Band"},
    {value: "book", text: "Book"},
    {value: "restaurant", text: "Restaurant"},
    {value: "trip", text: "Trip"},
    {value: "relationship", text: "Relationship"},
    {value: "friendship", text: "Friendship"},
    {value: "childhoodMilestones", text: "Childhood Milestones"},
    {value: "pet", text: "Pet"},
    {value: "job", text: "Job"},
    {value: "residence", text: "Residence"},
    {value: "school", text: "School"},
    {value: "eventWedding", text: "Wedding"},
    {value: "eventSports", text: "Sporting Event"},
    {value: "eventConcert", text: "Concert"},
    {value: "eventParty", text: "Party"},
    {value: "eventSomeoneElse", text: "Event for Someone Else"},
    {value: "achievementOrAward", text: "Achievement or Award"},
    {value: "majorPurchase", text: "Major Purchase"},
    {value: "lifeEvent", text: "Life Event"},
    {value: "picture", text: "Picture"},
    {value: "ticket", text: "Ticket"},
    {value: "financialAccount", text: "Financial Account"},
    {value: "other", text: "Other"}
];

exports.entryTypes = [
    "journalEntry", "thought", "otherNote", "movie", "show", 
    "song", "album", "band", "book", "restaurant", "trip", 
    "relationship", "friendship", "childhoodMilestones", "pet", 
    "job", "residence", "school", "eventWedding", "eventSports", 
    "eventConcert", "eventParty", "eventSomeoneElse", 
    "achievementOrAward", "majorPurchase", "lifeEvent", "picture", 
    "ticket", "financialAccount", "other"
];